version: "3.4"
services:
  nginx:
    image: nginx:latest
    env_file:
      - ../../.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../nginx/templates:/etc/nginx/templates:ro
      - ../../nginx/dhparam:/etc/nginx/dhparam:ro
      - ../../nginx/cloudflare:/etc/nginx/cloudflare:ro
    networks:
      - belega-network

networks:
  belega-network:
    external: true

