version: "3.4"
services:
  app:
    container_name: frontend-ecommerce-desa-belega
    image: ghcr.io/belega-village-unud/frontend-web-edb:v1
    env_file:
      - ../../.env
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - service

networks:
  service:
    driver: bridge
